Associations set up
Omwomo/school-library pull request #3
Opened 2023-10-26 14:41 UTC by Omwomo

- Created class Classroom with label attribute and association with Student class.
- Created the has-many/belongs-to relationship between Classroom and Student.
- Created Book and Rental classes.
- Created the many-to-many (also has-many-through) relationship between Person and Book using the intermediate class Rental.

2023-10-26 17:19 UTC, Alusp requested changes
Hi @Omwomo, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![close](https://media.giphy.com/media/nJKDTpuxnZE7fb6Z1b/giphy.gif)

## Highlights

- [ ] Descriptive PR Summary used 👍
- [ ] Completed most of the Tasks.👍
 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Alusp in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-26 17:19 UTC, Alusp commented on book.rb
> +  attr_reader :rentals
- [ ] Good job so far, :clap: However, Please use `attr_accessor` instead of `attr_reader` for your getters and setters for rentals that way you will be able to access rentals.
- [ ] Please make sure you initialize `:rentals` in your constructor.
- Possible solution would be to add `@rentals = []` just below `@author = author` :slightly_smiling_face: 

- [ ] According to the project requirement, you are suppose to have `a method for adding rentals` in your `Book` class, please resolve that. :slightly_smiling_face:

2023-10-26 17:19 UTC, Alusp commented on student.rb
- [ ] Good job so far, :clap: , however, As part of the requirement, please ensure that you have a method that serves as the `belongs-to` side (a student belongs to a classroom).
- Below is a possible solution: :arrow_down: 
>def classroom=(classroom)
       @classroom = classroom
       classroom.students.push(self) unless classroom.students.include?(self)
  end

2023-10-26 17:19 UTC, Alusp commented on rental.rb
> +  attr_accessor :date
- [ ] Please also add `:book` and `:person` to `:date` because they all require getters and setters.

2023-10-26 17:19 UTC, Alusp commented on person.rb
> +  attr_reader :id, :rentals
- [ ] Please ensure that your `:rentals` uses `attr_accessor` also. :slightly_smiling_face: 
- [ ] Please ensure that your `Person` class has `A method for adding rentals`

2023-10-26 17:19 UTC, Alusp commented on classroom.rb
> +    students << student
- [ ] Please ensure that you put `@` symbol in front of your `students` variable in your `add_students` method, that way you will be referring to your class attributes. A possible solution is: `@students << student` :slightly_smiling_face:

2023-10-27 06:13 UTC, prolajumokeoni commented on student.rb
Hi @Omwomo, you are yet to implement this change 👍🏿

2023-10-27 06:26 UTC, prolajumokeoni requested changes
Hi @Omwomo 
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights
✔️Associations created between classes for school library

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-27 06:26 UTC, prolajumokeoni commented on student.rb
>      super(age, name, parent_permission: parent_permission)
- [ ] Kindly add  a method that serves as the 'belongs-to' side (a student belongs to a classroom) just as the previous reviewer requested 👍🏿 

```
  def classroom=(classroom)
      @classroom = classroom
      classroom.students.push(self) unless classroom.students.include?(self)
  end
```

2023-10-27 06:42 UTC, Efiamotu-1 approved these changes
Hi @Omwomo, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)

## Highlights :dart: 
* Correct Gitflow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PR summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-27 07:22 UTC, merged