Write the unit test
Omwomo/school-library pull request #7
Opened 2023-11-02 14:22 UTC by axcell-0

In this project we implemented the following changes.

Added unit tests for all the methods in all the classes:
Book
Person
Student
Teacher
Classroom
Rental
all classes that you created while implementing the Decorator design pattern.

2023-11-02 15:18 UTC, danmainah requested changes
Hi @axcell-0 , @BiancaMe and @Omwomo , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Added tests for all the required classes except decoration classes.
✔️  Ensured all tests added are passing.


# Required Changes ♻️

- [ ] @Team You forgot to add tests for the classes that you created while implementing the Decorator design pattern, this is part of project requirement
![image](https://github.com/Omwomo/school-library/assets/61408860/63479368-1d30-4eea-9dd0-08019e0fd3a2)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-11-02 15:18 UTC, danmainah commented on spec/book_spec.rb
> +  end
- [ ] @Team Great work adding tests for the book classes, however you forgot to add tests for these methods ` add_rental, book_to_json, self.from_json, save_books and load_books`, its  project requirement to add tests for all methods
![image](https://github.com/Omwomo/school-library/assets/61408860/a1e0a748-ab1a-40c5-b631-9873c106c7df)

2023-11-02 15:18 UTC, danmainah commented on spec/person_spec.rb
> +  end
- [ ] @Team Great work adding tests for the person class, however you forgot to add tests for these methods ` people_to_json, self.from_json, add_rentals, self.find_by_id,  save_people and load_people`, its  project requirement to add tests for all methods
![image](https://github.com/Omwomo/school-library/assets/61408860/a1e0a748-ab1a-40c5-b631-9873c106c7df)

2023-11-02 15:18 UTC, danmainah commented on spec/teacher_spec.rb
> +  end
- [ ] @Team Great work adding tests for the teacher class, however you forgot to add test for this method  ` can_use_services`, its  project requirement to add tests for all methods
![image](https://github.com/Omwomo/school-library/assets/61408860/a1e0a748-ab1a-40c5-b631-9873c106c7df)

2023-11-02 15:18 UTC, danmainah commented on spec/classroom_spec.rb
> +    end
- [ ] @Team Great work adding tests for the classroom class, however you forgot to add test for this method  ` classroom=`, its  project requirement to add tests for all methods
![image](https://github.com/Omwomo/school-library/assets/61408860/a1e0a748-ab1a-40c5-b631-9873c106c7df)

2023-11-02 15:18 UTC, danmainah commented on spec/rental_spec.rb
> +    end
- [ ] @Team Great work adding tests for the rental class, however you forgot to add tests for these methods ` self.from_json, save_rental, load_rental`, its  project requirement to add tests for all methods
![image](https://github.com/Omwomo/school-library/assets/61408860/a1e0a748-ab1a-40c5-b631-9873c106c7df)

2023-11-03 17:00 UTC, Efiamotu-1 requested changes
Hi @Team, 

![](https://camo.githubusercontent.com/a06454929d29b512682cd8b375641b59076b9e5fe1a367808e685e5bcb818de3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a45784e32466d5957466c5a6a45794d7a49314f4455784d5455775a44686b595459355932526c4e6a4d334e7a4e6c4f574530596a4a684d695a6c634431324d563970626e526c636d35686246396e61575a7a583264705a6b6c6b4a6d4e305057632f7a3370696f6b77663057504838314d4f68752f67697068792e676966)

Great work on making the changes requested by a previous reviewer 👏 Your Code is Awesome! 💪
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-03 17:00 UTC, Efiamotu-1 commented on spec/rental_spec.rb
- [ ] As requested by the previous reviewer in this [review link](https://github.com/Omwomo/school-library/pull/7#discussion_r1380312580), you are yet to add test cases for the `save_rental & load_rental` please kindly do this :+1: :sparkles:

2023-11-03 17:00 UTC, Efiamotu-1 commented on spec/person_spec.rb
- [ ] As requested by the previous reviewer in this [review link](https://github.com/Omwomo/school-library/pull/7#discussion_r1380304087) you are yet to add tests for `self.from_json, self.find_by_id,`. Please kindly do this :+1:

2023-11-03 17:00 UTC, Efiamotu-1 commented on spec/book_spec.rb
- [ ] As requested by the previous reviewer in this [review link](https://github.com/Omwomo/school-library/pull/7#discussion_r1380295528) you are yet to add test for the method `self.from_json` please kindly add them :+1:

2023-11-04 00:34 UTC, Reem-lab approved these changes
# Hi Team,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3GBG7xejOXhH7MyQkn/giphy.gif"/>

## Highlights

- [ ]  Followed Gitflow 💯
- [ ]  Descriptive PR⭐
- [ ]  Kudos for working on the tests🤩
- [ ] All tests passed  🎉
- [ ] Good job working on the requested changes 🙏🏻


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-04 00:42 UTC, merged